# Generated by Django 5.2 on 2025-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
